{% set name = "jupyros" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyros-{{ version }}.tar.gz
  sha256: 6ecb1c7512903b155c42ad1865b05955771d90b997f25a6c1682d05d0b474090

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - jupyter_packaging
    - pip
  run:
    - python >=3.7
    - ipywidgets >=7.7.2,<8.0
    - bqplot
    - numpy
    - rospkg
    - ipycanvas
    - notebook

test:
  imports:
    - jupyros
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/RoboStack/jupyter-ros.git
  summary: Jupyter widgets for the ROS ecosystem.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ihuicatl
