{% set name = "jupyros" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyros-{{ version }}.tar.gz
  sha256: e21cb6cd7535076cb2bf93f9b1aef002a313a11922e0f39dab954512663a2877

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatch
    - hatchling
    - hatch-nodejs-version
    - hatch-jupyter-builder
  run:
    - python >={{ python_min }},<3.12
    - ipywidgets >=7.7.2,<8.0
    - bqplot
    - numpy
    - rospkg
    - ipycanvas
    - notebook <7.0

test:
  imports:
    - jupyros
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/RoboStack/jupyter-ros.git
  summary: Jupyter widgets for the ROS ecosystem.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ihuicatl
