{% set name = "jupyros" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyros-{{ version }}.tar.gz
  sha256: 0f55edbde842f5ec0b440c0b8b7bc1b962ad5017a1338bf6c88fa93b9a9774fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatch
    - pip
  run:
    - python >=3.9
    - ipywidgets
    - bqplot
    - numpy
    - rospkg
    - ipycanvas
    - notebook

test:
  imports:
    - jupyros
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/RoboStack/jupyter-ros.git
  summary: Jupyter widgets for the ROS ecosystem.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ihuicatl
